---
# https://docs.github.com/en/github/administering-a-repository/enabling-and-disabling-version-updates
version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
    assignees:
      - "uk-bolly"
    reviewers:
      - "uk-bolly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
    assignees:
      - "uk-bolly"
    reviewers:
      - "uk-bolly"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
    assignees:
      - "uk-bolly"
    reviewers:
      - "uk-bolly"

  - package-ecosystem: "pip"
    directory: "/docs"
    schedule:
      interval: "weekly"
      day: "saturday"
    assignees:
      - "uk-bolly"
    reviewers:
      - "uk-bolly"
