FROM debian:bullseye
LABEL org.opencontainers.image.authors="Ahmed"

RUN echo 'deb http://deb.debian.org/debian bullseye main contrib' > /etc/apt/sources.list
RUN echo 'deb http://deb.debian.org/debian bullseye-updates main contrib' >> /etc/apt/sources.list
RUN echo 'deb http://security.debian.org/debian-security/ bullseye-security main contrib' >> /etc/apt/sources.list

RUN apt-get -o Acquire::Check-Valid-Until=false update && apt-get install --yes \
    systemd-sysv apache2 ca-certificates tinyproxy dnsmasq && \
    apt-get clean

RUN (cd /lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i == systemd-tmpfiles-setup.service ] || rm -f $i; done); \
    rm -f /lib/systemd/system/multi-user.target.wants/*; \
    rm -f /etc/systemd/system/*.wants/*; \
    rm -f /lib/systemd/system/local-fs.target.wants/*; \
    rm -f /lib/systemd/system/sockets.target.wants/*udev*; \
    rm -f /lib/systemd/system/sockets.target.wants/*initctl*; \
    rm -f /lib/systemd/system/basic.target.wants/*; \
    rm -f /lib/systemd/system/anaconda.target.wants/*

RUN sed -i 's/Listen 80/Listen 0.0.0.0:80/g' /etc/apache2/ports.conf

COPY dnsmasq.conf /etc/dnsmasq.conf

RUN systemctl enable apache2 tinyproxy dnsmasq
RUN mkfifo /pipe
