FROM ubuntu:jammy
LABEL org.opencontainers.image.authors="Ahmed"

RUN apt-get update && \
    apt-get install --no-install-recommends -y systemd-sysv && \
    apt-get install -y apache2 tinyproxy dnsmasq && \
    apt-get clean

RUN (cd /lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i == systemd-tmpfiles-setup.service ] || rm -f $i; done); \
    rm -f /lib/systemd/system/multi-user.target.wants/*; \
    rm -f /etc/systemd/system/*.wants/*; \
    rm -f /lib/systemd/system/local-fs.target.wants/*; \
    rm -f /lib/systemd/system/sockets.target.wants/*udev*; \
    rm -f /lib/systemd/system/sockets.target.wants/*initctl*; \
    rm -f /lib/systemd/system/basic.target.wants/*; \
    rm -f /lib/systemd/system/anaconda.target.wants/*

RUN sed -i 's/Listen 80/Listen 0.0.0.0:80/g' /etc/apache2/ports.conf

COPY dnsmasq.conf /etc/dnsmasq.conf

RUN mkdir -p /var/log/tinyproxy && chown tinyproxy:tinyproxy /var/log/tinyproxy

RUN mkdir -p /etc/systemd/system/tinyproxy.service.d && \
    printf '[Service]\nType=simple\nExecStart=\nExecStart=/usr/bin/tinyproxy -d\nPIDFile=\nPrivateDevices=no\n' > /etc/systemd/system/tinyproxy.service.d/override.conf

RUN systemctl enable apache2 tinyproxy dnsmasq
RUN mkfifo /pipe
